spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 12345678
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 718046731869-lmv6di5depcgngtuk6m24kh86unt71bs.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: qw22847@gmail.com
  secret_key: springboot-blog-dev